#!/usr/local/bin/php
<?php declare(strict_types=1);

$_ENV['LAMBDA_TASK_ROOT'] ??= '/var/task';
$_ENV['_HANDLER'] ??= 'index';

require_once "{$_ENV['LAMBDA_TASK_ROOT']}/{$_ENV['_HANDLER']}.php";
require_once __DIR__ . '/vendor/autoload.php';
$api = new Runtime\API($_ENV['AWS_LAMBDA_RUNTIME_API']);

Co\run(static function() use ($api): void {
    while (true) {
        try {
            $api->response(main($api->next()));
        } catch (\Throwable $err) {
            $api->error($err);
        }
    }
});
